name: Build
'on':
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build Hugo example sites and archive output
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build Hugo example site with image
        run: |
          cd tests/exampleSiteWithImage/
          hugo --verbose --baseURL= --themesDir=../../../

      - name: Upload Hugo example site with image
        uses: actions/upload-artifact@v4
        with:
          name: hugo-example-site
          path: tests/exampleSiteWithImage/public

      - name: Build Hugo example site with video
        run: |
          cd tests/exampleSiteWithVideo/
          hugo --verbose --baseURL= --themesDir=../../../

      - name: Upload Hugo example site with video
        uses: actions/upload-artifact@v4
        with:
          name: hugo-example-site
          path: tests/exampleSiteWithVideo/public
